# Generated by Django 4.0 on 2021-12-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
                ('ratting', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('facebook_page', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
