# Generated by Django 4.0.4 on 2022-05-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment2', 'payment2'), ('payment1', 'payment1'), ('payment3', 'payment3')], default='payment3', max_length=20),
        ),
        migrations.CreateModel(
            name='Customer_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('quantity', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('area', models.TextField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('image', models.FileField(upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
