# Generated by Django 4.0.4 on 2022-05-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_order_delivery_type_customer_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_post',
            name='contact',
        ),
    ]
