# Generated by Django 4.0 on 2021-12-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('image', models.FileField(upload_to='')),
                ('prev_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creation_date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.restaurant')),
            ],
        ),
    ]
