# Generated by Django 4.0.4 on 2022-05-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_post_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Post',
            new_name='CustomerPost',
        ),
    ]
