# Generated by Django 4.0 on 2022-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
