# Generated by Django 4.0.4 on 2022-05-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customerpost_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpost',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
