# Generated by Django 4.0.4 on 2022-05-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerpost_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpost',
            name='foundation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.foundation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment1', 'payment1'), ('payment3', 'payment3'), ('payment2', 'payment2')], default='payment3', max_length=20),
        ),
    ]
