# Generated by Django 4.0.4 on 2022-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customerpost_foundation_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment1', 'payment1'), ('payment2', 'payment2'), ('payment3', 'payment3')], default='payment3', max_length=20),
        ),
    ]
