# Generated by Django 4.0 on 2022-01-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.category'),
        ),
    ]
