# Generated by Django 4.0.3 on 2022-05-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment2', 'payment2'), ('payment3', 'payment3'), ('payment1', 'payment1')], default='payment3', max_length=20),
        ),
    ]
