# Generated by Django 4.0.1 on 2022-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
