# Generated by Django 4.0.1 on 2022-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Cart', 'Cart'), ('Active', 'Active'), ('Delivered', 'Delivered')], default='Active', max_length=20),
        ),
    ]
