# Generated by Django 4.0.1 on 2022-01-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_remove_cart_restaurant_alter_cart_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.restaurant'),
        ),
    ]
