# Generated by Django 4.0.1 on 2022-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_cart_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
