# Generated by Django 4.0.1 on 2022-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_cart_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
