# Generated by Django 4.0.1 on 2022-01-24 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0020_cart_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
                ('code_no', models.CharField(max_length=15, null=True)),
                ('Doe', models.CharField(max_length=15, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foundation_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('items', models.TextField(max_length=100)),
                ('quantity', models.TextField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('area', models.TextField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.foundation')),
            ],
        ),
    ]
