# Generated by Django 4.0.1 on 2022-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_foundation_foundation_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
