# Generated by Django 4.0.3 on 2022-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_foundation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_sub_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
