# Generated by Django 4.0.3 on 2022-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_delivery_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_man',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
