# Generated by Django 4.0.3 on 2022-03-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_remove_cart_delivery_date_remove_cart_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
