# Generated by Django 4.0.3 on 2022-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_delivery_man_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_man',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
