# Generated by Django 4.0.3 on 2022-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_remove_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rand_order_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
