# Generated by Django 4.0.3 on 2022-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sub_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
