# Generated by Django 4.0.3 on 2022-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
