# Generated by Django 4.0.3 on 2022-03-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment1', 'payment1'), ('payment3', 'payment3'), ('payment2', 'payment2')], default='payment3', max_length=20),
        ),
    ]
