# Generated by Django 4.0.3 on 2022-04-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_delivery_man_type'),
        ('customers', '0031_order_delivery_type'),
    ]

    operations = [
    ]
