# Generated by Django 4.0.3 on 2022-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_merge_0025_delivery_man_type_0031_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment3', 'payment3'), ('payment1', 'payment1'), ('payment2', 'payment2')], default='payment3', max_length=20),
        ),
    ]
