# Generated by Django 4.0.3 on 2022-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('payment2', 'payment2'), ('payment1', 'payment1'), ('payment3', 'payment3')], default='payment3', max_length=20),
        ),
    ]
